// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ruby.DAL;

#nullable disable

namespace Ruby.DAL.Migrations
{
    [DbContext(typeof(RubyDBContext))]
    [Migration("20260228181056_Added_RefreshTokens_table")]
    partial class Added_RefreshTokens_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ruby.DAL.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ClassicRock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PunkRock"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grunge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AlternativeRock"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IndieRock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "HeavyMetal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ThrashMetal"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Techno"
                        },
                        new
                        {
                            Id = 102,
                            Name = "House"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Trance"
                        },
                        new
                        {
                            Id = 104,
                            Name = "DrumAndBass"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Dubstep"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Synthwave"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Ambient"
                        },
                        new
                        {
                            Id = 201,
                            Name = "OldSchoolHipHop"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Trap"
                        },
                        new
                        {
                            Id = 203,
                            Name = "ContemporaryRnB"
                        },
                        new
                        {
                            Id = 301,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 302,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 303,
                            Name = "Funk"
                        },
                        new
                        {
                            Id = 304,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 401,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 402,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 403,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 404,
                            Name = "Reggae"
                        });
                });

            modelBuilder.Entity("Ruby.DAL.Entities.LikeEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.PlaylistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Title");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.PlaylistTrackEntity", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("playlist_tracks", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.RefreshTokensEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreationAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.TrackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AudioFileKey")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("audio_file_key");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("CoverImageKey")
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Title");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.TrackGenreEntity", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("track_genres", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Ruby.DAL.Entities.LikeEntity", b =>
                {
                    b.HasOne("Ruby.DAL.Entities.TrackEntity", "Track")
                        .WithMany("Likes")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ruby.DAL.Entities.UserEntity", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.PlaylistEntity", b =>
                {
                    b.HasOne("Ruby.DAL.Entities.UserEntity", "Creator")
                        .WithMany("Playlists")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.PlaylistTrackEntity", b =>
                {
                    b.HasOne("Ruby.DAL.Entities.PlaylistEntity", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ruby.DAL.Entities.TrackEntity", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.RefreshTokensEntity", b =>
                {
                    b.HasOne("Ruby.DAL.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.TrackEntity", b =>
                {
                    b.HasOne("Ruby.DAL.Entities.UserEntity", "Author")
                        .WithMany("Tracks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.TrackGenreEntity", b =>
                {
                    b.HasOne("Ruby.DAL.Entities.GenreEntity", "Genre")
                        .WithMany("TrackGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ruby.DAL.Entities.TrackEntity", "Track")
                        .WithMany("TrackGenres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.GenreEntity", b =>
                {
                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.PlaylistEntity", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.TrackEntity", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("Ruby.DAL.Entities.UserEntity", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Playlists");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
